name: CI - Unit + Integration (.NET 9)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./ShopCaseStudy.sln

      - name: Build (Release)
        run: dotnet build ./ShopCaseStudy.sln -c Release --no-restore -p:TreatWarningsAsErrors=false

      - name: Run UnitTests
        run: dotnet test ./tests/UnitTests/UnitTests.csproj -c Release --no-build --logger "trx;LogFileName=unit.trx"

  integration-tests:
    runs-on: ubuntu-latest
    needs: build-and-unit-test

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shop_db
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd "pg_isready -U user -d shop_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
      redis:
        image: redis:7-alpine
        ports: [ "6379:6379" ]
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    env:
      ConnectionStrings__DefaultConnection: "Host=127.0.0.1;Port=5432;Database=shop_db;Username=user;Password=password"
      ConnectionStrings__Redis: "127.0.0.1:6379,abortConnect=false"

      Jwt__Issuer: "Shop.Api"
      Jwt__Audience: "Shop.Api.Client"
      Jwt__Key: "INSECURE_CI_ONLY_32CHARS_MINIMUM_123456"

      DISABLE_RATE_LIMITING: "true"

      # Program.cs AddApplicationServices mediatR key istiyorsa dummy ver:
      MEDIATR_LICENSE_KEY: "CI_DUMMY_KEY"

      ASPNETCORE_ENVIRONMENT: "Development"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./ShopCaseStudy.sln

      - name: Build (Release)
        run: dotnet build ./ShopCaseStudy.sln -c Release --no-restore -p:TreatWarningsAsErrors=false

      - name: Wait for Postgres & Redis
        shell: bash
        run: |
          echo "Waiting Postgres..."
          for i in {1..60}; do
            pg_isready -h 127.0.0.1 -p 5432 -U user && break
            sleep 2
          done
          echo "Waiting Redis..."
          for i in {1..60}; do
            (echo > /dev/tcp/127.0.0.1/6379) >/dev/null 2>&1 && break
            sleep 2
          done

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet-ef to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Apply EF migrations
        run: |
          dotnet ef database update \
            --project ./src/Infrastructure/Infrastructure.csproj \
            --startup-project ./src/Api/Api.csproj


      - name: Run IntegrationTests
        run: dotnet test ./tests/IntegrationTests/IntegrationTests.csproj -c Release --no-build --logger "trx;LogFileName=integration.trx"
